name: woostore_pro
description: WooStore Pro is a new Flutter application for Ecommerce and fully compatible with WooCommerce.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.2+38

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  eva_icons_flutter: ^3.0.2
  another_flushbar: ^1.10.24
  auto_route: ^3.2.0
  flutter_facebook_auth: ^3.5.1
  flutter_form_builder:
    git: https://github.com/Sportner/flutter_form_builder.git
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  google_sign_in: ^5.1.0
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  introduction_screen: ^2.1.0
  photo_view: ^0.12.0
  logger: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.0.8
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.2
#  flutter_swiper: ^1.1.6
  card_swiper: ^1.0.4
  event_bus: ^2.0.0
  # WooCommerce
  woocommerce: 
    path: ../packages/woocommerce
  dio: ^4.0.0
  flutter_rating_bar: ^4.0.0
  shimmer: ^2.0.0
  expandable: ^5.0.1
  webview_flutter: ^2.0.14
  package_info: ^2.0.2
  badges: ^2.0.1
  flutter_countdown_timer: ^4.1.0
  dropdown_search: ^1.0.0
  # Firebase
  firebase_messaging: ^10.0.7
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_dynamic_links: ^2.0.9
  # Local Notifications
  flutter_local_notifications: ^8.2.0
  flutter_html: ^2.1.2
  # Localization
  flutter_localizations:
    sdk: flutter
  # Database
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # Share
  share_plus: ^2.1.4
  font_awesome_flutter: ^9.1.0
  intl_utils: #^2.4.0
    git:
      url: https://github.com/luis901101/intl_utils.git
      ref: depedencies_update

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^3.2.0
  build_runner: null
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/dental.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/svg/
    - lib/assets/svg/flags/
    - lib/assets/json/
    - lib/assets/gifs/
flutter_intl:
  enabled: true
  use_deferred_loading: true